FROM oven/bun:1.3.8 AS builder
WORKDIR /app

COPY bun.lock package.json turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages
COPY turbo ./turbo

RUN bun install --frozen-lockfile --linker=hoisted
RUN cd apps/server && bun build --compile --minify --bytecode --target=bun-linux-x64 ./src/serve.ts --outfile server

FROM debian:bookworm-slim AS runner
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app/apps/server/server ./server
COPY --from=builder /app/packages/db/src/migrations ./migrations

EXPOSE 3000
CMD ["./server"]
