FROM oven/bun:1.3.8 AS base
WORKDIR /app

COPY bun.lock package.json turbo.json tsconfig.json ./
COPY apps ./apps
COPY packages ./packages

RUN bun install --frozen-lockfile --linker=hoisted

FROM base AS builder
COPY . .
RUN bun run build --filter server

FROM oven/bun:1.3.8 AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/apps/server/dist ./apps/server/dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/bun.lock ./bun.lock

EXPOSE 3000
CMD ["bun", "apps/server/dist/index.mjs"]
